// Datos mock de productos (en un caso real vendría de la API)
export const productData = [
  {
    id: "1",
    name: "AMD Ryzen 7 7800X3D",
    price: 1399,
    originalPrice: 1549,
    category: "Procesadores",
    images: [
      "/AMD-Ryzen-7-7800X3D.jpg",
      "/AMD-Ryzen-7-7800X3D.jpg",
      "/AMD-Ryzen-7-7800X3D.jpg",
    ],
    description:
      "Experiencia de juego de primera línea con la tecnología de memoria de los procesadores de alta calidad de ASUS Dual que potencian las mejores del mercado. Obtén aún más rendimiento con este procesador de vanguardia que acelera cada proyecto desde...",
    specs: {
      model: "Ryzen 7 7800X3D",
      series: "Ryzen 7000 Series",
      generation: "Computadoras de escritorio, Procesadores de alta",
      segment: "Enthusiast Desktop",
      productSupport: "No",
      productId: "NM-100000XXMHX",
      productIdentification: "YD7800X3XXAFLH",
    },
    features: {
      delivery: { icon: "🚚", text: "Envío Gratis", detail: "En más de" },
      warranty: { icon: "📅", text: "1 año", detail: "Garantía" },
      payment: { icon: "💳", text: "Hasta", detail: "12 cuotas" },
    },
  },
  {
    id: "2",
    name: "Masterliquid 240L Core ARGB",
    price: 425,
    originalPrice: 500,
    category: "Refrigeración",
    images: [
      "/masterliquid-240l-rgb-liquid-cooler.jpg",
      "/masterliquid-240l-rgb-liquid-cooler.jpg",
      "/masterliquid-240l-rgb-liquid-cooler.jpg",
    ],
    description:
      "Sistema de refrigeración líquida de alto rendimiento con iluminación RGB personalizable. Ideal para mantener temperaturas óptimas en procesadores de alta gama durante sesiones intensas de gaming y trabajo profesional.",
    specs: {
      model: "240L Core ARGB",
      series: "MasterLiquid",
      generation: "Refrigeración líquida, Coolers de alta gama",
      segment: "Gaming Desktop",
      productSupport: "Sí",
      productId: "ML-240L-ARGB",
      productIdentification: "CL240ARGB001",
    },
    features: {
      delivery: { icon: "🚚", text: "Envío Gratis", detail: "En más de" },
      warranty: { icon: "📅", text: "2 años", detail: "Garantía" },
      payment: { icon: "💳", text: "Hasta", detail: "12 cuotas" },
    },
  },
  {
    id: "3",
    name: "Portátil Gamer Acer Nitro",
    price: 4430,
    originalPrice: 4800,
    category: "Laptops",
    images: [
      "/acer-nitro-gaming-laptop.png",
      "/acer-nitro-gaming-laptop.png",
      "/acer-nitro-gaming-laptop.png",
    ],
    description:
      "Laptop gaming de alto rendimiento con Intel Core i7 y RTX 3050. Perfecta para gaming y trabajo profesional con pantalla de 16 pulgadas y almacenamiento M.2 ultra rápido.",
    specs: {
      model: "Nitro Lite 16",
      series: "Acer Nitro",
      generation: "Laptops gaming, Portátiles de alta gama",
      segment: "Gaming Mobile",
      productSupport: "Sí",
      productId: "AC-NITRO-16-I7",
      productIdentification: "ACNITRO16RTX3050",
    },
    features: {
      delivery: { icon: "🚚", text: "Envío Gratis", detail: "En más de" },
      warranty: { icon: "📅", text: "1 año", detail: "Garantía" },
      payment: { icon: "💳", text: "Hasta", detail: "18 cuotas" },
    },
  },
  {
    id: "4",
    name: "Astro A50 X Gaming Headset",
    price: 1599,
    originalPrice: 1800,
    category: "Audio",
    images: [
      "/astro-a50-x-gaming-headset.webp",
      "/astro-a50-x-gaming-headset.webp",
      "/astro-a50-x-gaming-headset.webp",
    ],
    description:
      "Diadema gaming inalámbrica premium con audio espacial y cancelación de ruido. Compatible con PC, PlayStation y Xbox para una experiencia de audio inmersiva.",
    specs: {
      model: "A50 X",
      series: "Astro Gaming",
      generation: "Audio gaming, Headsets inalámbricos",
      segment: "Premium Audio",
      productSupport: "Sí",
      productId: "AST-A50X-WL",
      productIdentification: "ASTROA50XGAMING",
    },
    features: {
      delivery: { icon: "🚚", text: "Envío Gratis", detail: "En más de" },
      warranty: { icon: "📅", text: "1 año", detail: "Garantía" },
      payment: { icon: "💳", text: "Hasta", detail: "12 cuotas" },
    },
  },
  {
    id: "5",
    name: "AMD Ryzen 5 5500X3D",
    price: 1437,
    originalPrice: 1600,
    category: "Procesadores",
    images: [
      "/AMD-Ryzen-5-5500X3D.webp",
      "/AMD-Ryzen-5-5500X3D.webp",
      "/AMD-Ryzen-5-5500X3D.webp",
    ],
    description:
      "Procesador AMD Ryzen 5 con tecnología 3D V-Cache para gaming de alto rendimiento. Perfecto para jugadores que buscan el máximo FPS en sus juegos favoritos.",
    specs: {
      model: "Ryzen 5 5500X3D",
      series: "Ryzen 5000 Series",
      generation: "Computadoras de escritorio, Procesadores gaming",
      segment: "Gaming Desktop",
      productSupport: "No",
      productId: "AMD-R5-5500X3D",
      productIdentification: "YD5500X3DHBOX",
    },
    features: {
      delivery: { icon: "🚚", text: "Envío Gratis", detail: "En más de" },
      warranty: { icon: "📅", text: "1 año", detail: "Garantía" },
      payment: { icon: "💳", text: "Hasta", detail: "12 cuotas" },
    },
  },
  {
    id: "6",
    name: "AMD Ryzen 5 7800F",
    price: 510,
    originalPrice: 600,
    category: "Procesadores",
    images: [
      "/AMD-Ryzen-5-7800F.webp",
      "/AMD-Ryzen-5-7800F.webp",
      "/AMD-Ryzen-5-7800F.webp",
    ],
    description:
      "Procesador AMD Ryzen 5 de nueva generación. Excelente rendimiento para gaming y productividad a un precio accesible.",
    specs: {
      model: "Ryzen 5 7800F",
      series: "Ryzen 7000 Series",
      generation: "Computadoras de escritorio, Procesadores mainstream",
      segment: "Mainstream Desktop",
      productSupport: "Sí",
      productId: "AMD-R5-7800F",
      productIdentification: "YD7800FHBOX",
    },
    features: {
      delivery: { icon: "🚚", text: "Envío Gratis", detail: "En más de" },
      warranty: { icon: "📅", text: "1 año", detail: "Garantía" },
      payment: { icon: "💳", text: "Hasta", detail: "12 cuotas" },
    },
  },
  {
    id: "7",
    name: "Intel Core Ultra 5 245K",
    price: 550,
    originalPrice: 650,
    category: "Procesadores",
    images: [
      "/Intel-Core-Ultra-5-245K.webp",
      "/Intel-Core-Ultra-5-245K.webp",
      "/Intel-Core-Ultra-5-245K.webp",
    ],
    description:
      "Procesador Intel Core Ultra de última generación con tecnología de IA integrada. Perfecto para gaming y creación de contenido.",
    specs: {
      model: "Core Ultra 5 245K",
      series: "Intel Core Ultra",
      generation: "Computadoras de escritorio, Procesadores Ultra",
      segment: "Gaming Desktop",
      productSupport: "Sí",
      productId: "INTEL-CU5-245K",
      productIdentification: "BX8071245K",
    },
    features: {
      delivery: { icon: "🚚", text: "Envío Gratis", detail: "En más de" },
      warranty: { icon: "📅", text: "1 año", detail: "Garantía" },
      payment: { icon: "💳", text: "Hasta", detail: "12 cuotas" },
    },
  },
  {
    id: "8",
    name: "Intel Core Ultra 7 265K",
    price: 1499,
    originalPrice: 1650,
    category: "Procesadores",
    images: [
      "/Intel-Core-Ultra-7-265K.webp",
      "/Intel-Core-Ultra-7-265K.webp",
      "/Intel-Core-Ultra-7-265K.webp",
    ],
    description:
      "Procesador Intel Core Ultra 7 de alta gama con máximo rendimiento para gaming y productividad profesional.",
    specs: {
      model: "Core Ultra 7 265K",
      series: "Intel Core Ultra",
      generation: "Computadoras de escritorio, Procesadores Ultra",
      segment: "Enthusiast Desktop",
      productSupport: "Sí",
      productId: "INTEL-CU7-265K",
      productIdentification: "BX8071265K",
    },
    features: {
      delivery: { icon: "🚚", text: "Envío Gratis", detail: "En más de" },
      warranty: { icon: "📅", text: "1 año", detail: "Garantía" },
      payment: { icon: "💳", text: "Hasta", detail: "12 cuotas" },
    },
  },
  {
    id: "10",
    name: "AMD Ryzen 9 9950X3D",
    price: 1600,
    originalPrice: 1800,
    category: "Procesadores",
    images: [
      "/AMD-Ryzen-9-9950X3D.jpg",
      "/AMD-Ryzen-9-9950X3D.jpg",
      "/AMD-Ryzen-9-9950X3D.jpg",
    ],
    description:
      "El procesador más potente de AMD con tecnología 3D V-Cache de nueva generación. Para los usuarios más exigentes.",
    specs: {
      model: "Ryzen 9 9950X3D",
      series: "Ryzen 9000 Series",
      generation: "Computadoras de escritorio, Procesadores 3D V-Cache",
      segment: "Enthusiast Desktop",
      productSupport: "Sí",
      productId: "AMD-R9-9950X3D",
      productIdentification: "YD9950X3DHBOX",
    },
    features: {
      delivery: { icon: "🚚", text: "Envío Gratis", detail: "En más de" },
      warranty: { icon: "📅", text: "1 año", detail: "Garantía" },
      payment: { icon: "💳", text: "Hasta", detail: "12 cuotas" },
    },
  },
  {
    id: "12",
    name: "Intel Core Ultra 9 285",
    price: 1399,
    originalPrice: 1550,
    category: "Procesadores",
    images: [
      "/Intel-Core-Ultra-9-285.jpg",
      "/Intel-Core-Ultra-9-285.jpg",
      "/Intel-Core-Ultra-9-285.jpg",
    ],
    description:
      "Procesador Intel Core Ultra 9 de gama alta. Rendimiento excepcional para gaming y aplicaciones profesionales.",
    specs: {
      model: "Core Ultra 9 285",
      series: "Intel Core Ultra",
      generation: "Computadoras de escritorio, Procesadores Ultra",
      segment: "Enthusiast Desktop",
      productSupport: "Sí",
      productId: "INTEL-CU9-285",
      productIdentification: "BX8071285",
    },
    features: {
      delivery: { icon: "🚚", text: "Envío Gratis", detail: "En más de" },
      warranty: { icon: "📅", text: "1 año", detail: "Garantía" },
      payment: { icon: "💳", text: "Hasta", detail: "12 cuotas" },
    },
  },
];

export const categories = [
  "Procesadores",
  "Refrigeración",
  "Laptops",
  "Audio",
  "GPU",
  "Board",
  "Almacenamiento",
  "Fuente",
  "Chasis",
  "Memoria",
];
